---

- name: Install Packages 
  apt: name={{item}}
  with_items:
    - htop
    - mc
    - tmux
    - screen
    - docker.io
    - golang-1.10-go
    - nmap
    - jq
    - unzip
    - mariadb-client-core-10.1
    - elixir
    - mongodb
    - mongodb-server-core
    - mongodb-clients
